version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: udyam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DB_HOST=db
      DB_NAME=udyam_db
      DB_USER=postgres
      DB_PASSWORD=password
      DB_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend

volumes:
  db_data:
